from email.policy import default

from . import db


def profile_description():
    text = """【表格名称】profiles
    【表格描述】用于存储用户档案信息。
    【字段描述】
    - uid, int, 用户UID
    - real_name, str, 真实姓名
    - alias, str, 别名
    - gender, str, 性别， male或female
    - birth_date, str, 出生日期, 格式YYYY-MM-DD
    - native_place, str, 籍贯
    - education, str, 学历的英文，例如'bachelor'、'master'、'doctor'等
    - student_id, int, 学工号
    - position, str, 职务，例如讲师、教授等
    - contact, str, 联系电话
    - address, str, 备注
    - party_committee, str, 对应branches表中的value字段, 表示用户所属的党委, 例如'committee1'
    - party_subcommittee, str, 对应branches表中的value字段, 表示用户所属的党总支, 例如'subcommittee11'
    - party_branch, str, 对应branches表中的value字段, 表示用户所属的党支部, 例如'branch111'
    - party_status, str, 党内职务名称, 例如支部委员、支部书记等
    - join_date, str, 成为党员的日期, 格式YYYY-MM-DD
    - admin_status, int, 管理员状态, 0: 普通用户, 1: 管理员，只有管理员可以审核用户发起的任务和通知。
    
    """
    return text


class Profile(db.Model):
    __tablename__ = 'profiles'
    uid = db.Column('uid', db.Integer, db.ForeignKey('users.uid'), primary_key=True, unique=True, index=True, nullable=False)
    real_name = db.Column('real_name', db.Text, nullable=False)
    alias = db.Column('alias', db.Text, nullable=True, default='')
    gender = db.Column('gender', db.Text, nullable=True, default='male')
    birth_date = db.Column('birth_date', db.Text, nullable=True)
    native_place = db.Column('native_place', db.Text, nullable=True)
    education = db.Column('education', db.Text, nullable=True, default='bachelor')
    student_id = db.Column('student_id', db.Integer, nullable=False, default='0')  # 学工号字段
    position = db.Column('position', db.Text, nullable=True)
    contact = db.Column('contact', db.Text, nullable=True)
    address = db.Column('address', db.Text, nullable=True)  # 备注字段
    party_committee = db.Column('party_committee', db.Text, nullable=True)
    party_subcommittee = db.Column('party_subcommittee', db.Text, nullable=True)
    party_branch = db.Column('party_branch', db.Text, nullable=True)
    party_status = db.Column('party_status', db.Text, nullable=True)
    join_date = db.Column('join_date', db.Text, nullable=True)
    admin_status = db.Column('admin_status', db.Integer, nullable=False, default=0)
    # 建立与User模型的关系
    user = db.relationship('User', backref=db.backref('profile', uselist=False))


def init_profiles():
    # 初始化测试用户档案
    if not Profile.query.first():
        default_profile = [
            Profile(uid=101, real_name='杨小二', alias='yth',
                    gender='male',
                    birth_date='1990-04-13', native_place='浙江宁波',
                    position='副教授',
                    student_id=1, contact='14274457379',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='支部委员',
                    join_date='1900-01-01',
                    admin_status=1),
            Profile(uid=102, real_name='朱小二', alias='zxf',
                    gender='male',
                    birth_date='1980-04-13', native_place='浙江宁波',
                    position='副教授',
                    student_id=1, contact='13434635773',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='支部书记',
                    join_date='1900-01-01',
                    admin_status=1),
            Profile(uid=103, real_name='和小二', alias='htx',
                    gender='male',
                    birth_date='1988-04-13', native_place='浙江宁波',
                    position='讲师',
                    student_id=1, contact='14623636893',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=104, real_name='邵小二', alias='szy',
                    gender='female',
                    birth_date='1995-04-13', native_place='浙江杭州',
                    position='讲师',
                    student_id=1, contact='18768492130',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=105, real_name='何小二', alias='hhh',
                    gender='male',
                    birth_date='1999-04-13', native_place='浙江杭州',
                    position='讲师',
                    student_id=1, contact='15302935822',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=106, real_name='王小二', alias='ww',
                    gender='female',
                    birth_date='1994-04-13', native_place='浙江金华',
                    position='讲师',
                    student_id=1, contact='18392033432',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=107, real_name='董小二', alias='djj',
                    gender='female',
                    birth_date='1993-04-13', native_place='湖北武汉',
                    position='讲师',
                    student_id=1, contact='13596854773',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=108, real_name='叶小二', alias='yhf',
                    gender='male',
                    birth_date='1989-04-13', native_place='山西太原',
                    position='讲师',
                    student_id=1, contact='18433923028',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=109, real_name='郑小二', alias='zly',
                    gender='male',
                    birth_date='1988-04-13', native_place='山西太原',
                    position='讲师',
                    student_id=1, contact='19948739584',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=110, real_name='孙小二', alias='sgq',
                    gender='male',
                    birth_date='1985-04-13', native_place='上海',
                    position='讲师',
                    student_id=1, contact='15329445837',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=111, real_name='刘小二', alias='lyr',
                    gender='female',
                    birth_date='1999-04-13', native_place='浙江宁波',
                    position='讲师',
                    student_id=1, contact='19533285391',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='支部委员',
                    join_date='1900-01-01',
                    admin_status=1),
            Profile(uid=112, real_name='吴小二', alias='wj',
                    gender='male',
                    birth_date='1988-04-13', native_place='浙江杭州',
                    position='高级工程师',
                    student_id=1, contact='13291884733',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=113, real_name='马小二', alias='ml',
                    gender='male',
                    birth_date='1975-04-13', native_place='浙江杭州',
                    position='工程师',
                    student_id=1, contact='13255943302',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=114, real_name='游小二', alias='ylc',
                    gender='male',
                    birth_date='1980-04-13', native_place='浙江杭州',
                    position='实验师',
                    student_id=1, contact='18433293028',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=115, real_name='杨小二', alias='yp',
                    gender='male',
                    birth_date='1987-04-13', native_place='浙江杭州',
                    position='讲师',
                    student_id=1, contact='17438223928',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=116, real_name='姚小二', alias='yl',
                    gender='male',
                    birth_date='1990-04-13', native_place='浙江杭州',
                    position='副教授',
                    student_id=1, contact='18437284930',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=117, real_name='席小二', alias='xnl',
                    gender='female',
                    birth_date='1990-05-13', native_place='浙江杭州',
                    position='助理工程师',
                    student_id=1, contact='18739203392',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='支部委员',
                    join_date='1900-01-01',
                    admin_status=1),
            Profile(uid=118, real_name='陶小二', alias='ty',
                    gender='female',
                    birth_date='1990-06-13', native_place='浙江杭州',
                    position='副教授',
                    student_id=1, contact='18738292210',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='支部书记',
                    join_date='1900-01-01',
                    admin_status=1),
            Profile(uid=119, real_name='辛小二', alias='xjy',
                    gender='male',
                    birth_date='1975-07-13', native_place='浙江金华',
                    position='副教授',
                    student_id=1, contact='18374432890',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='支部委员',
                    join_date='1900-01-01',
                    admin_status=1),
            Profile(uid=120, real_name='李小二', alias='lk',
                    gender='male',
                    birth_date='1970-08-13', native_place='浙江丽水',
                    position='教授',
                    student_id=1, contact='18333274933',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='支部委员',
                    join_date='1900-01-01',
                    admin_status=1),
            Profile(uid=121, real_name='周小二', alias='zh',
                    gender='male',
                    birth_date='1990-09-15', native_place='浙江丽水',
                    position='讲师',
                    student_id=1, contact='18733281948',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=122, real_name='钟小二', alias='zfr',
                    gender='female',
                    birth_date='2002-04-13', native_place='浙江丽水',
                    position='无',
                    student_id=1, contact='19238274465',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=123, real_name='孔小二', alias='ky',
                    gender='female',
                    birth_date='1990-04-13', native_place='浙江衢州',
                    position='讲师',
                    student_id=1, contact='12947394485',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='支部书记',
                    join_date='1900-01-01',
                    admin_status=1),
            Profile(uid=124, real_name='王小二', alias='wf',
                    gender='female',
                    birth_date='2003-12-13', native_place='浙江绍兴',
                    position='无',
                    student_id=1, contact='19388748339',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=125, real_name='肖小二', alias='xx',
                    gender='female',
                    birth_date='2003-02-13', native_place='浙江温州',
                    position='无',
                    student_id=1, contact='14439484456',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=126, real_name='张小二', alias='zfl',
                    gender='female',
                    birth_date='12003-01-13', native_place='浙江温州',
                    position='无',
                    student_id=1, contact='19433854765',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=127, real_name='张小二', alias='zyf',
                    gender='male',
                    birth_date='2003-11-13', native_place='浙江温州',
                    position='无',
                    student_id=1, contact='19877654893',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=128, real_name='张小二', alias='zpp, zip',
                    gender='male',
                    birth_date='2003-04-13', native_place='浙江湖州',
                    position='无',
                    student_id=1, contact='19344753827',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=129, real_name='方小二', alias='fcc',
                    gender='female',
                    birth_date='2003-04-13', native_place='江西九江',
                    position='无',
                    student_id=1, contact='17658322938',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=130, real_name='刘小二', alias='lmh',
                    gender='female',
                    birth_date='2002-04-13', native_place='江西九江',
                    position='无',
                    student_id=1, contact='17544632837',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=131, real_name='郭小二', alias='gxx',
                    gender='female',
                    birth_date='2001-04-13', native_place='浙江绍兴',
                    position='无',
                    student_id=1, contact='18755634756',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=132, real_name='唐小二', alias='tjl',
                    gender='male',
                    birth_date='2004-04-13', native_place='浙江绍兴',
                    position='无',
                    student_id=4003230303, contact='18756432324',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='预备党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=133, real_name='王小二', alias='wyy',
                    gender='female',
                    birth_date='2004-04-13', native_place='浙江绍兴',
                    position='无',
                    student_id=1, contact='17655374654',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=134, real_name='袁小二', alias='ypy',
                    gender='female',
                    birth_date='2004-05-11', native_place='浙江杭州',
                    position='无',
                    student_id=1, contact='18756453375',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=135, real_name='胡小二', alias='hhx',
                    gender='male',
                    birth_date='1988-04-13', native_place='浙江杭州',
                    position='工程师',
                    student_id=1, contact='19857564488',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='支部书记',
                    join_date='1900-01-01',
                    admin_status=1),
            Profile(uid=136, real_name='许小二', alias='xmx, star',
                    gender='male',
                    birth_date='1995-04-13', native_place='浙江杭州',
                    position='讲师',
                    student_id=1, contact='18765543782',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='支部委员',
                    join_date='1900-01-01',
                    admin_status=1),
            Profile(uid=137, real_name='蒋小二', alias='jwq',
                    gender='male',
                    birth_date='2003-04-13', native_place='浙江杭州',
                    position='无',
                    student_id=4003230117, contact='18756438873',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='预备党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=138, real_name='王小二', alias='wyj',
                    gender='female',
                    birth_date='2004-04-13', native_place='浙江杭州',
                    position='无',
                    student_id=4003230228, contact='17768493328',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='预备党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=139, real_name='索小二', alias='shr',
                    gender='male',
                    birth_date='1990-04-13', native_place='浙江杭州',
                    position='副教授',
                    student_id=1, contact='16657483394',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=140, real_name='王小二', alias='wyc',
                    gender='female',
                    birth_date='2003-04-13', native_place='浙江杭州',
                    position='无',
                    student_id=1, contact='15573648837',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=141, real_name='李小二', alias='lsw',
                    gender='male',
                    birth_date='2000-04-13', native_place='浙江杭州',
                    position='无',
                    student_id=1, contact='15644732837',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch111',
                    party_status='普通正式党员',
                    join_date='1900-01-01',
                    admin_status=0),
            Profile(uid=142, real_name='黄小二', alias='hhy',
                    gender='female',
                    birth_date='1991-04-13', native_place='浙江宁波',
                    position='助教',
                    student_id=1, contact='18755643384',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='支部委员',
                    join_date='1900-01-01',
                    admin_status=1),
            Profile(uid=143, real_name='冯小二', alias='fyy',
                    gender='male',
                    birth_date='2004-06-20', native_place='浙江宁波',
                    position='无',
                    student_id=6401230103, contact='18768594590',
                    address='无',
                    party_committee='committee1',
                    party_subcommittee='subcommittee11',
                    party_branch='branch112',
                    party_status='预备党员',
                    join_date='1900-01-01',
                    admin_status=0)
        ]
        db.session.bulk_save_objects(default_profile)
        db.session.commit()
        print("初始化测试用户档案完成.")